/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SuppliersRouteImport } from "./routes/suppliers"
import { Route as CustomersRouteImport } from "./routes/customers"
import { Route as IndexRouteImport } from "./routes/index"

const SuppliersRoute = SuppliersRouteImport.update({
  id: "/suppliers",
  path: "/suppliers",
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: "/customers",
  path: "/customers",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/customers": typeof CustomersRoute
  "/suppliers": typeof SuppliersRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/customers": typeof CustomersRoute
  "/suppliers": typeof SuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/customers": typeof CustomersRoute
  "/suppliers": typeof SuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/customers" | "/suppliers"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/customers" | "/suppliers"
  id: "__root__" | "/" | "/customers" | "/suppliers"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  SuppliersRoute: typeof SuppliersRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/suppliers": {
      id: "/suppliers"
      path: "/suppliers"
      fullPath: "/suppliers"
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/customers": {
      id: "/customers"
      path: "/customers"
      fullPath: "/customers"
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  SuppliersRoute: SuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
